Repository eccentriccoder01/SaralSeva, pull requests merged in 2025-08, with the labels that each got.

#19 Feature Request: Add Contact Form with Necessary Details
  backend/models/contactModel.js
  backend/routes/contactRoutes.js
  backend/server.js
  user/src/components/Contact.jsx
Labels: enhancement, gssoc25, level 3

#36 fix(ui): Update social media icons and add `tel:` link for phone
  user/src/components/pages/Footer.jsx
Labels: bug, gssoc25, level 1

#37 Added autocomment workflows for PR and Issues
  .github/issue-create-automate-message.yml
  .github/pr-create-automate-message.yml
Labels: gssoc25, level 1

#39 Fix dark mode functionality across FAQ page
  user/src/components/Faq.jsx
Labels: bug, gssoc25, level 1
