Repository eccentriccoder01/SaralSeva, pull requests merged in 2025-10, with the labels that each got.

#143 Enhanced background with flag in waving motion
  user/src/index.css
Labels: enhancement, gssoc25, level 3

#151 Removed the unnecessary toggle dark-light mode button
  user/src/components/PrivacyPolicy.jsx
Labels: gssoc25, level 2

#160 🎨 UX Enhancement : Add close button and overlay click-to-dismiss for QR popup (Issue #158)
  user/src/components/pages/Footer.jsx
Labels: bug, gssoc25, level 2

#140 Add new available government schemes data
  backend/data/schemes.json
  backend/scripts/seedSchemes.js
  backend/server.js
Labels: enhancement, gssoc25, level 3

#166 Restructured Register page UI
  user/src/components/pages/login-register/Register.jsx
Labels: enhancement, gssoc25, level 2

#167 Fixes #135
  admin/src/App.jsx
  admin/src/components/NotFound.jsx
  employee/src/App.jsx
  employee/src/components/NotFound.jsx
  user/src/App.jsx
  user/src/components/NotFound.jsx
Labels: enhancement, gssoc25, level 2
