Repository eccentriccoder01/SaralSeva, pull requests merged in 2025-09, with the labels that each got.

#49 Enhanced Code of Conduct with Visuals, GIFs, Emojis, and Contributors Wall ✨
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, gssoc25, level 1

#68 docs: Add alt text to main logo for accessibility
  README.md
Labels: gssoc25, level 1

#90 feat(footer): enlarge QR code on click and make store links functional
  user/src/components/pages/Footer.jsx
Labels: enhancement, gssoc25, level 2

#95 Remove debug console.log statements from production code
  admin/src/components/Announcement.jsx
  admin/src/components/context/adminContext.jsx
  backend/controllers/schemesController.js
  employee/src/components/SingleGrievance.jsx
  employee/src/components/SingleTicket.jsx
  employee/src/components/context/EmployeeContext.jsx
  user/src/components/context/SchemaContext.jsx
  user/src/components/pages/login-register/CompleteGoogleRegistration.jsx
  user/src/components/pages/login-register/Register.jsx
  user/src/components/pages/login-register/UserLogin.jsx
  user/src/components/pages/login-register/VerifyOtp.jsx
  user/src/components/pages/scheme/Scheme.jsx
Labels: gssoc25, level 2

#99 Enhance dark mode functionality by initializing from localStorage
  user/src/components/Topbar.jsx
Labels: bug, gssoc25, level 2

#100 Refine Feedback Button Positioning
  employee/package-lock.json
  user/src/components/FeedbackButton.jsx
  user/src/components/chatbot/Chatbot.css
Labels: bug, gssoc25, level 2

#121 chore(security): add Dependabot automation + security docs for monorepo
  .github/dependabot.yml
  DEPENDABOT.md
  README.md
  SECURITY.md
Labels: documentation, gssoc25, level 2, security

#136 Fix: clear contact form fields after successful submission
  user/src/components/Contact.jsx
Labels: bug, gssoc25, level 2

#137 Fixed the alignment of cards
  user/src/components/Grievances.jsx
Labels: gssoc25, level 2

#133 feat: add health monitoring endpoint (monitorP1 + health route) #109
  .gitignore
  backend/.gitignore
  backend/middleware/security.js
  backend/monitor/monitorP1.js
  backend/routes/health.js
  backend/server.js
  package-lock.json
  package.json
Labels: gssoc25, level 2
